from configparser import ConfigParser

global_config = {
    "boris@pozdena.eu": {
        "config_file": "/home/bob/.config/onedrive/accounts/boris@pozdena.eu/config",
        "enable_debug": "True",
        "mode": "monitor",
        "onedrive": {
            "sync_dir": '"/home/bob/OneDrive/"',
            "skip_file": '"~*|.~*|*.tmp|*.txt|*.exe|.testfile"',
            "monitor_interval": '"15"',
            "skip_dir": '"__pycache__|env|venv"',
            "log_dir": '"/var/log/onedrive/"',
            "drive_id": '""',
            "upload_only": '"false"',
            "check_nomount": '"false"',
            "check_nosync": '"false"',
            "download_only": '"false"',
            "disable_notifications": '"false"',
            "disable_upload_validation": '"false"',
            "enable_logging": '"false"',
            "force_http_2": '"false"',
            "local_first": '"false"',
            "no_remote_delete": '"false"',
            "skip_symlinks": '"false"',
            "debug_https": '"false"',
            "skip_dotfiles": '"false"',
            "dry_run": '"false"',
            "min_notify_changes": '"5"',
            "monitor_log_frequency": '"5"',
            "monitor_fullscan_frequency": '"1"',
            "sync_root_files": '"false"',
            "classify_as_big_delete": '"1000"',
            "user_agent": '""',
            "remove_source_files": '"false"',
            "skip_dir_strict_match": '"false"',
            "application_id": '""',
            "resync": '"false"',
            "bypass_data_preservation": '"false"',
            "azure_ad_endpoint": '""',
            "azure_tenant_id": '"common"',
            "sync_business_shared_folders": '"false"',
            "sync_dir_permissions": '"700"',
            "sync_file_permissions": '"600"',
            "rate_limit": '"185700000"',
            "operation_timeout": '"3600"',
            "webhook_enabled": '"false"',
            "webhook_public_url": '""',
            "webhook_listening_host": '""',
            "webhook_listening_port": '"8888"',
            "webhook_expiration_interval": '"86400"',
            "webhook_renewal_interval": '"43200"',
        },
    },
    "bpozdena@gmail.com": {
        "config_file": "/home/bob/.config/onedrive/accounts/pozdenab@gmail.com/config",
        "enable_debug": "True",
        "mode": "monitor",
        "onedrive": {
            "sync_dir": '"~/OneDrive222"',
            "skip_file": '"~*|.~*|*.tmp|*.txt|*.exe"',
            "monitor_interval": '"15"',
            "skip_dir": '"__pycache__|env|venv|ignore_filder"',
            "log_dir": '"/var/log/onedrive/"',
            "drive_id": '""',
            "upload_only": '"false"',
            "check_nomount": '"false"',
            "check_nosync": '"false"',
            "download_only": '"false"',
            "disable_notifications": '"false"',
            "disable_upload_validation": '"false"',
            "enable_logging": '"false"',
            "force_http_2": '"false"',
            "local_first": '"false"',
            "no_remote_delete": '"false"',
            "skip_symlinks": '"false"',
            "debug_https": '"false"',
            "skip_dotfiles": '"false"',
            "dry_run": '"false"',
            "min_notify_changes": '"5"',
            "monitor_log_frequency": '"5"',
            "monitor_fullscan_frequency": '"1"',
            "sync_root_files": '"false"',
            "classify_as_big_delete": '"1000"',
            "user_agent": '""',
            "remove_source_files": '"false"',
            "skip_dir_strict_match": '"false"',
            "application_id": '""',
            "resync": '"false"',
            "bypass_data_preservation": '"false"',
            "azure_ad_endpoint": '""',
            "azure_tenant_id": '"common"',
            "sync_business_shared_folders": '"false"',
            "sync_dir_permissions": '"700"',
            "sync_file_permissions": '"600"',
            "rate_limit": '"185700000"',
            "operation_timeout": '"3600"',
            "webhook_enabled": '"false"',
            "webhook_public_url": '""',
            "webhook_listening_host": '""',
            "webhook_listening_port": '"8888"',
            "webhook_expiration_interval": '"86400"',
            "webhook_renewal_interval": '"43200"',
        },
    },
}



test = {}
test['onedrive'] = global_config['boris@pozdena.eu']

od_config = ConfigParser()

print(test)


od_config.read_dict(test)

print(od_config)