# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'setup_wizard.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QWidget, QWizard,
    QWizardPage)

class Ui_SetupWizard(object):
    def setupUi(self, SetupWizard):
        if not SetupWizard.objectName():
            SetupWizard.setObjectName(u"SetupWizard")
        SetupWizard.resize(640, 480)
        SetupWizard.setMinimumSize(QSize(640, 480))
        SetupWizard.setMaximumSize(QSize(640, 480))
        SetupWizard.setWizardStyle(QWizard.ClassicStyle)
        self.wizardPage_welcome = QWizardPage()
        self.wizardPage_welcome.setObjectName(u"wizardPage_welcome")
        self.label = QLabel(self.wizardPage_welcome)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 80, 271, 18))
        self.label_2 = QLabel(self.wizardPage_welcome)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 200, 441, 20))
        SetupWizard.setPage(1, self.wizardPage_welcome)
        self.wizardPage_version_check = QWizardPage()
        self.wizardPage_version_check.setObjectName(u"wizardPage_version_check")
        self.label_3 = QLabel(self.wizardPage_version_check)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 80, 171, 18))
        self.label_4 = QLabel(self.wizardPage_version_check)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 80, 211, 18))
        self.label_5 = QLabel(self.wizardPage_version_check)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 160, 531, 111))
        SetupWizard.setPage(2, self.wizardPage_version_check)
        self.wizardPage_create_import = QWizardPage()
        self.wizardPage_create_import.setObjectName(u"wizardPage_create_import")
        self.label_6 = QLabel(self.wizardPage_create_import)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 70, 481, 18))
        self.checkBox_create = QCheckBox(self.wizardPage_create_import)
        self.checkBox_create.setObjectName(u"checkBox_create")
        self.checkBox_create.setGeometry(QRect(30, 140, 171, 22))
        self.checkBox_import = QCheckBox(self.wizardPage_create_import)
        self.checkBox_import.setObjectName(u"checkBox_import")
        self.checkBox_import.setGeometry(QRect(30, 180, 251, 22))
        SetupWizard.setPage(3, self.wizardPage_create_import)
        self.wizardPage_import = QWizardPage()
        self.wizardPage_import.setObjectName(u"wizardPage_import")
        self.label_7 = QLabel(self.wizardPage_import)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 60, 291, 18))
        self.label_profile_name = QLabel(self.wizardPage_import)
        self.label_profile_name.setObjectName(u"label_profile_name")
        self.label_profile_name.setGeometry(QRect(7, 166, 107, 32))
#if QT_CONFIG(tooltip)
        self.label_profile_name.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.label_profile_name.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_config_path = QLabel(self.wizardPage_import)
        self.label_config_path.setObjectName(u"label_config_path")
        self.label_config_path.setGeometry(QRect(7, 210, 107, 32))
#if QT_CONFIG(tooltip)
        self.label_config_path.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.label_config_path.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_profile_name = QLineEdit(self.wizardPage_import)
        self.lineEdit_profile_name.setObjectName(u"lineEdit_profile_name")
        self.lineEdit_profile_name.setGeometry(QRect(120, 166, 308, 32))
        self.lineEdit_config_path = QLineEdit(self.wizardPage_import)
        self.lineEdit_config_path.setObjectName(u"lineEdit_config_path")
        self.lineEdit_config_path.setGeometry(QRect(120, 210, 308, 32))
        self.pushButton_import = QPushButton(self.wizardPage_import)
        self.pushButton_import.setObjectName(u"pushButton_import")
        self.pushButton_import.setGeometry(QRect(120, 310, 391, 34))
        SetupWizard.setPage(4, self.wizardPage_import)
        self.wizardPage_create = QWizardPage()
        self.wizardPage_create.setObjectName(u"wizardPage_create")
        self.label_10 = QLabel(self.wizardPage_create)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(40, 70, 231, 18))
        self.lineEdit_sync_dir = QLineEdit(self.wizardPage_create)
        self.lineEdit_sync_dir.setObjectName(u"lineEdit_sync_dir")
        self.lineEdit_sync_dir.setGeometry(QRect(145, 219, 249, 32))
        self.lineEdit_new_profile_name = QLineEdit(self.wizardPage_create)
        self.lineEdit_new_profile_name.setObjectName(u"lineEdit_new_profile_name")
        self.lineEdit_new_profile_name.setGeometry(QRect(145, 180, 249, 32))
        self.label_new_profile_name = QLabel(self.wizardPage_create)
        self.label_new_profile_name.setObjectName(u"label_new_profile_name")
        self.label_new_profile_name.setGeometry(QRect(30, 180, 109, 32))
        self.label_sync_dir = QLabel(self.wizardPage_create)
        self.label_sync_dir.setObjectName(u"label_sync_dir")
        self.label_sync_dir.setGeometry(QRect(30, 219, 109, 32))
        self.pushButton_create = QPushButton(self.wizardPage_create)
        self.pushButton_create.setObjectName(u"pushButton_create")
        self.pushButton_create.setGeometry(QRect(170, 340, 351, 34))
        SetupWizard.setPage(5, self.wizardPage_create)
        self.wizardPage_finish = QWizardPage()
        self.wizardPage_finish.setObjectName(u"wizardPage_finish")
        self.label_13 = QLabel(self.wizardPage_finish)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 80, 591, 171))
        self.label_13.setWordWrap(True)
        SetupWizard.setPage(6, self.wizardPage_finish)

        self.retranslateUi(SetupWizard)

        QMetaObject.connectSlotsByName(SetupWizard)
    # setupUi

    def retranslateUi(self, SetupWizard):
        SetupWizard.setWindowTitle(QCoreApplication.translate("SetupWizard", u"Wizard", None))
        self.label.setText(QCoreApplication.translate("SetupWizard", u"Welcome to OneDriveGUI", None))
        self.label_2.setText(QCoreApplication.translate("SetupWizard", u"This wizard will help you with initial OneDrive profile creation/import.", None))
        self.label_3.setText(QCoreApplication.translate("SetupWizard", u"Installed OneDrive version:", None))
        self.label_4.setText(QCoreApplication.translate("SetupWizard", u"Installed/Not Installed/ version", None))
        self.label_5.setText(QCoreApplication.translate("SetupWizard", u"<html><head/><body><p><span style=\" font-family:'Droid Sans Mono','monospace','monospace','Droid Sans Fallback'; font-size:14px; color:#960000;\">OneDrive Client for Linux does not seem to be installed. </span></p><pre style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:19px; background-color:#272822;\"><span style=\" font-family:'Droid Sans Mono','monospace','monospace','Droid Sans Fallback'; font-size:14px; color:#960000;\">Please install it by following </span><a href=\"https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md\"><span style=\" font-family:'Hack'; text-decoration: underline; color:#960000;\">instructions</span></a><span style=\" font-family:'Droid Sans Mono','monospace','monospace','Droid Sans Fallback'; font-size:14px; color:#960000;\"> for your distro. </span></pre></body></html>", None))
        self.label_6.setText(QCoreApplication.translate("SetupWizard", u"Would you like to create a new OneDrive profile or import existing one?", None))
        self.checkBox_create.setText(QCoreApplication.translate("SetupWizard", u"Create new profile", None))
        self.checkBox_import.setText(QCoreApplication.translate("SetupWizard", u"Import existing profile/config. ", None))
        self.label_7.setText(QCoreApplication.translate("SetupWizard", u"Import existing profile/config", None))
        self.label_profile_name.setText(QCoreApplication.translate("SetupWizard", u"Profile Name", None))
        self.label_config_path.setText(QCoreApplication.translate("SetupWizard", u"Path to config file", None))
        self.lineEdit_profile_name.setPlaceholderText(QCoreApplication.translate("SetupWizard", u"E.g. john@live.com", None))
        self.lineEdit_config_path.setPlaceholderText(QCoreApplication.translate("SetupWizard", u"E.g. ~/.config/onedrive/config", None))
        self.pushButton_import.setText(QCoreApplication.translate("SetupWizard", u"Import profile", None))
        self.label_10.setText(QCoreApplication.translate("SetupWizard", u"Create new profile", None))
        self.lineEdit_sync_dir.setPlaceholderText(QCoreApplication.translate("SetupWizard", u"E.g. ~/OneDrive_john@live.com/", None))
        self.lineEdit_new_profile_name.setPlaceholderText(QCoreApplication.translate("SetupWizard", u"E.g. john@live.com", None))
        self.label_new_profile_name.setText(QCoreApplication.translate("SetupWizard", u"New profile name", None))
        self.label_sync_dir.setText(QCoreApplication.translate("SetupWizard", u"Sync directory", None))
        self.pushButton_create.setText(QCoreApplication.translate("SetupWizard", u"Create new profile", None))
        self.label_13.setText(QCoreApplication.translate("SetupWizard", u"<html><head/><body><p>Your OneDrive profile has been created. </p><p><br/></p><p>You can adjust advanced profile options if needed. Once you are happy with the profile settings, start sync with OneDrive. You will be automatically presented with a OneDrive login page if you have not logged on previously.</p></body></html>", None))
    # retranslateUi

